// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositorioAcademico.Server.Infrastructure.Data;

#nullable disable

namespace RepositorioAcademico.Server.Migrations
{
    [DbContext(typeof(RepositorioDbContext))]
    [Migration("20260426015617_AddDocumentDownloadPolicy")]
    partial class AddDocumentDownloadPolicy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FacultadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("RutaDocumento")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("SePuedeDescargar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultadId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.Facultad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Facultades");
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "DASHBOARD.VER",
                            Descripcion = "Visualizar panel principal",
                            Estado = "Activo"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "REPOSITORIO.VER",
                            Descripcion = "Visualizar el repositorio academico",
                            Estado = "Activo"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "DOCUMENTO.SUBIR",
                            Descripcion = "Subir nuevos documentos",
                            Estado = "Activo"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "DOCUMENTO.PUBLICAR",
                            Descripcion = "Publicar o revisar documentos pendientes",
                            Estado = "Activo"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "CATALOGO.GESTIONAR",
                            Descripcion = "Gestionar facultades y tipos de documento",
                            Estado = "Activo"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "USUARIO.GESTIONAR",
                            Descripcion = "Crear y administrar usuarios",
                            Estado = "Activo"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "ROL.GESTIONAR",
                            Descripcion = "Crear y administrar roles",
                            Estado = "Activo"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "DOCUMENTO.DESCARGAR",
                            Descripcion = "Descargar documentos autorizados",
                            Estado = "Activo"
                        });
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Acceso total al sistema",
                            Estado = "Activo",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Puede ver repositorio y subir documentos",
                            Estado = "Activo",
                            Nombre = "Profesor"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Solo consulta el repositorio",
                            Estado = "Activo",
                            Nombre = "Estudiante"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Puede revisar y publicar documentos",
                            Estado = "Activo",
                            Nombre = "Decano"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Puede revisar y publicar documentos",
                            Estado = "Activo",
                            Nombre = "Director"
                        });
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolPermisos");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            PermisoId = 1,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 2,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 3,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 4,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 5,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 6,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 7,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 1,
                            PermisoId = 8,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 1,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 2,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 3,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 2,
                            PermisoId = 8,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 1,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 2,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 3,
                            PermisoId = 8,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 1,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 2,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 3,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 4,
                            PermisoId = 4,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 1,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 2,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 3,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RolId = 5,
                            PermisoId = 4,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TiposDocumento");
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Carnet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Carnet")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Sistema",
                            Carnet = "ADMIN-001",
                            Correo = "admin@universidad.edu",
                            Estado = "Activo",
                            FechaCreacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc),
                            Nombres = "Admin",
                            PasswordHash = "100000.pXNersvxrQkQJwCgdjOmBw==.R3lKdXVfKoq45g4VJKg0ZswpiAHqMqrq7VqFvBKyvyA="
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Docente",
                            Carnet = "PROF-001",
                            Correo = "profesor@universidad.edu",
                            Estado = "Activo",
                            FechaCreacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc),
                            Nombres = "Paula",
                            PasswordHash = "100000.pXNersvxrQkQJwCgdjOmBw==.R3lKdXVfKoq45g4VJKg0ZswpiAHqMqrq7VqFvBKyvyA="
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Estudiante",
                            Carnet = "EST-001",
                            Correo = "estudiante@universidad.edu",
                            Estado = "Activo",
                            FechaCreacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc),
                            Nombres = "Luis",
                            PasswordHash = "100000.pXNersvxrQkQJwCgdjOmBw==.R3lKdXVfKoq45g4VJKg0ZswpiAHqMqrq7VqFvBKyvyA="
                        },
                        new
                        {
                            Id = 4,
                            Apellidos = "Decano",
                            Carnet = "DEC-001",
                            Correo = "decano@universidad.edu",
                            Estado = "Activo",
                            FechaCreacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc),
                            Nombres = "Marta",
                            PasswordHash = "100000.pXNersvxrQkQJwCgdjOmBw==.R3lKdXVfKoq45g4VJKg0ZswpiAHqMqrq7VqFvBKyvyA="
                        });
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("UsuarioRoles");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            RolId = 1,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UsuarioId = 2,
                            RolId = 2,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UsuarioId = 3,
                            RolId = 3,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UsuarioId = 4,
                            RolId = 4,
                            Estado = "Activo",
                            FechaAsignacion = new DateTime(2026, 4, 25, 4, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.Documento", b =>
                {
                    b.HasOne("RepositorioAcademico.Server.Domain.Facultad", "Facultad")
                        .WithMany("Documentos")
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RepositorioAcademico.Server.Domain.TipoDocumento", "TipoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facultad");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.RolPermiso", b =>
                {
                    b.HasOne("RepositorioAcademico.Server.Domain.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RepositorioAcademico.Server.Domain.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.UsuarioRol", b =>
                {
                    b.HasOne("RepositorioAcademico.Server.Domain.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RepositorioAcademico.Server.Domain.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.Facultad", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.TipoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("RepositorioAcademico.Server.Domain.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
